### ISSUE TITLE
Unable to import cupcake.tofu! Please make sure you install cupcake.

### ISSUE THREAD

**Issue by ulloaa** [ConesaLab/SQANTI-SIM#13]
Hello, I am having an issue with commit baa765f:

`sqanti-sim.py classif --help`
`Unable to import cupcake.tofu! Please make sure you install cupcake.`

After installing as follows:

`mamba create -n sqanti-sim --yes python==3.10.11 -f SQANTI-SIM.conda_env.yml'
'mamba activate sqanti-sim`
`mamba install bioconda::pbsim3`

The previous commit install fine with the method above. Am I missing a dependency perhaps?

Thank you for your feedback on this!

**Comment by TianYuan-Liu** [comment]
Hi @ulloaa ,

Thanks for flagging this! It looks like commit  went out with a missing symbolic link, which prevents cupcake.tofu from being found at runtime. I’ve pushed a fix on main.

Could you please:
```
git pull origin main         # or just `git pull` if you’re already tracking main
```
After updating, sqanti-sim.py classif --help should run without the import error. Let me know if you still hit any issues and I’ll jump on it right away.

Thanks again for spotting this!

**Comment by KatPardo** [comment]
I just tried running the Sqanti-SIM sim step on my data and I received the following error in logs:

ERROR: No PBSIM3 SAM/BAM output found

I used data that had been ran on the previous version is Sqanti-SIM classif and Sqanti-SIM design - will this interfere with running that output data using the latest versions of Sqanti-sim for the sim module?

**Comment by TianYuan-Liu** [comment]
> I just tried running the Sqanti-SIM sim step on my data and I received the following error in logs:
> 
> ERROR: No PBSIM3 SAM/BAM output found
> 
> I used data that had been ran on the previous version is Sqanti-SIM classif and Sqanti-SIM design - will this interfere with running that output data using the latest versions of Sqanti-sim for the sim module?

Thanks for reaching out @KatPardo !

Could you please try running the sim step again using a new output folder, just to ensure there are no conflicts with previous intermediate files?

If the issue persists, could you kindly share the specific input file(s) you’re using so I can try to reproduce the error on my end and help troubleshoot further?

**Comment by KatPardo** [comment]
Unfortunately the issue still persists. I have emailed the three necessary input files required for the simulation module to generate long-read pac-bio data because I am unable to attach them here.
